### ISSUE TITLE
Show hitboxes

### ISSUE THREAD

**Issue by Mark137139** [Prevter/OpenHack#107]
Is it possible to add a "Show Hitboxes" hack to show the hitboxes like MegaHack with the same options for it as MegaHack?

**Comment by Clonerclo** [comment]
O Same! I really want hitboxes to the hack.

**Comment by Rustring** [comment]
Here is the link that has show hitboxes, from yesterday's commit (Geode only)
https://www.mediafire.com/file/trfa3p850fr4fvz/prevter.openhack.geode/file

**Comment by Rustring** [comment]
Here is the link that has show hitboxes, from yesterday's commit (Geode only)
https://github.com/Prevter/GDOpenHack/actions/runs/8333240586/artifacts/1336656597

**Comment by Mark137139** [comment]
@Rustring  how install?

**Comment by Mark137139** [comment]
it says it virus

**Comment by TobyAdd** [comment]
💀

**Comment by TobyAdd** [comment]
Don't use it if you think Windows Defender is smarter than your brain

**Comment by Rustring** [comment]
> Don't use it if you think Windows Defender is smarter than your brain

I use Linux haha
