### ISSUE TITLE
Copy Hack Bug

### ISSUE THREAD

**Issue by RAYYANAHNAFF** [Prevter/OpenHack#115]
copy hack doesn't work

**Comment by Rustring** [comment]
Provide more info

**Comment by gdsarajevo** [comment]
basically there is no copy symbol for levels that dont have a copy mark even for password-required levels, still got to enter a password, hope it helps

**Comment by Rustring** [comment]
Are u on the sandstone or the geode version, I am on the geode version and it works normally

**Comment by Kacper8698** [comment]
.

**Comment by Prevter** [comment]
Closing this as stale, no explanation provided.
