### ISSUE TITLE
[Bug] Right clicking doesn't work

### ISSUE THREAD

**Issue by Rustring** [Prevter/OpenHack#123]
I want to add a shortcut for show hitboxes but I can't

![Screenshot_20240321_115940](https://github.com/Prevter/OpenHack/assets/155897302/62f617e2-26aa-4de7-bc1e-519011a58dce)

Right clicking everything else works

![Screenshot_20240321_120127](https://github.com/Prevter/OpenHack/assets/155897302/cc8a9db4-6b60-4330-a1a8-3b2ea79f6c46)

**Comment by Prevter** [comment]
Looks like I missed it, will fix

**Comment by AbsoluteDasher** [comment]
now i can't left click for some things
