### ISSUE TITLE
im using the geode version and hack verify doesnt work [Bug]

### ISSUE THREAD

**Issue by jaquaviousquan** [Prevter/OpenHack#126]
**Describe the bug**
its still making me verify even though i have the verify hack thing on

**To Reproduce**
What steps did you do to get this result?

**Expected behavior**
publish the level without verifying it

**Screenshots**
![Screenshot 2024-03-23 174338](https://github.com/Prevter/OpenHack/assets/161180367/15e58573-4aa4-4ef2-aeae-b435a2c52789)

**Comment by Marcoiscool123** [comment]
You need to have anti cheat bypass on for verify hack to work.

**Comment by Rustring** [comment]
I think it's fixed now
https://github.com/Prevter/OpenHack/actions/runs/8405952679/artifacts/1352999231
