### ISSUE TITLE
[Bug] Show Hitboxes on Death shows hitboxes during gameplay in practice mode

### ISSUE THREAD

**Issue by TrueSunGaming** [Prevter/OpenHack#128]
**Describe the bug**
When Show Hitboxes on Death is enabled (Show Hitboxes is disabled in OpenHack and in game settings) and playing in practice mode, hitboxes are displayed all the time instead of only after death.

**To Reproduce**
1. Enable Show Hitboxes on Death
2. Enter a level
3. Enter practice mode

**Expected behavior**
Hitboxes only shown after death.

**Screenshots**
![image](https://github.com/Prevter/OpenHack/assets/79117622/566591be-2138-4ded-aee3-a37a837c59e8)

**Comment by Askar4iklol** [comment]
do u have enabled show hitboxes in practice mode ? this option is in geometry dash not openhack

**Comment by Prevter** [comment]
This is intentional, as I've tried to save base game functionality. You can just disable "Show Hitboxes" in the pause menu settings, and it should make hitboxes non-visible in practice mode.

**Comment by TrueSunGaming** [comment]
I have Show Hitboxes disabled in the pause settings, but they still appear
![image](https://github.com/Prevter/OpenHack/assets/79117622/86bcf49a-d657-43bf-8432-56616060c6f9)

**Comment by Prevter** [comment]
Can't reproduce,
Maybe you have an incompatible mod installed (perhaps some other mod menu with hitboxes).
Also, toggling "Show Hitboxes" in pause settings may not apply until after you re-enter the level.
