### ISSUE TITLE
[Bug]GD Keeps crashing whenever I open it with the geode version of openhack (I dont know if it still crashes when I download the non geode version)

### ISSUE THREAD

**Issue by WhoSaysViolet** [Prevter/OpenHack#129]
![1](https://github.com/Prevter/OpenHack/assets/150871770/a4dc1391-f655-49bf-8dbf-58e1e037bf74)
![2](https://github.com/Prevter/OpenHack/assets/150871770/2abe355b-10be-4924-8a50-5457040db591)
![3](https://github.com/Prevter/OpenHack/assets/150871770/b91fde74-91dc-403b-89da-4a16e8fbfc67)
**Describe the bug**

**To Reproduce**
What steps did you do to get this result?

**Expected behavior**

**Screenshots**

**Comment by Rustring** [comment]
Either download the latest version
https://github.com/Prevter/OpenHack/actions/runs/8405952679/artifacts/1352999231

Or delete your config file in your Local AppData GD directory then geode then mods then preeter.openhack

**Comment by WhoSaysViolet** [comment]
Thank you, dude.... I can finally use open hack being stuck with prism for 2 weeks
