### ISSUE TITLE
new update[Question]

### ISSUE THREAD

**Issue by Marcoiscool123** [Prevter/OpenHack#138]
hey just wondering how can you get the beta of the next update.

**Comment by Rustring** [comment]
Go to https://github.com/Prevter/OpenHack/actions select the commit update and download the build artifacts

**Comment by Rustring** [comment]
If you want a direct download (of the latest version as of writing this) here it is
Geode: https://github.com/Prevter/OpenHack/actions/runs/8456741389/artifacts/1364145980
Sandstone: https://github.com/Prevter/OpenHack/actions/runs/8456741386/artifacts/1364146862
