### ISSUE TITLE
[Bug]cant pause the game

### ISSUE THREAD

**Issue by TripleBaconn** [Prevter/OpenHack#148]
**Describe the bug**
when i pause, game crashes

**To Reproduce**
press escape in a level

**Expected behavior**
i can pause levels

**Screenshots**

(https://www.youtube.com/watch?v=J6T0RND0fSM)

**Comment by Prevter** [comment]
That's one of your mods crashing, openhack doesn't change anything about pause menu.
I would recommend first to update all of your mods and then if it doesn't help, disable mods that can be responsible (BetterPause does appear in your crashlogs, you can start with that)

**Comment by TripleBaconn** [comment]
> That's one of your mods crashing, openhack doesn't change anything about pause menu. I would recommend first to update all of your mods and then if it doesn't help, disable mods that can be responsible (BetterPause does appear in your crashlogs, you can start with that)

ok ill try gimme a sec
