### ISSUE TITLE
[Fixed bug] Fill hitboxes bug in practice mode

### ISSUE THREAD

**Issue by ReaLeCHL** [Prevter/OpenHack#149]
I have 'Show hitboxes on death' on, with 'Fill hitboxes' on as well. It works as expected in normal mode, but in practice mode, the hitboxes are always shown even without dying. Not only that, but also, while the hitboxes are shown, they aren't filled and the hitboxes are only filled once the player dies.

**Comment by x1st3nt** [comment]
I think Prevter already said that the hitboxes are always shown in practice mode and is intentional

**Comment by ReaLeCHL** [comment]
Well the hitboxes still aren't filled with 'Fill Hitboxes' even in practice mode until you die. Also the only thing that is filled is the player hitbox without dying yet

**Comment by ReaLeCHL** [comment]
Also is the player hitbox appearing at the bottom of the ground intentional?

**Comment by silvernull** [comment]
For me, the hitboxes always show afterwards with "Show Hitboxes on Death" enabled if i die in practice.
