### ISSUE TITLE
Use Explorers, the challenge, and spinoff music on levels[Request]

### ISSUE THREAD

**Issue by wi000000** [Prevter/OpenHack#154]
When making a level, one must choose a song to play in the background. There are many options. One could choose a song from the Newgrounds library, from GD's own music library, or one can use the songs used in the 22 official levels (IDs 1-22). However, the game still has more music that cannot be used for user levels:
23 - Explorers
24-26 - Meltdown music
27 - Secret (song used in The Challenge)
28-37 - World music
38-40 - Subzero music
One cannot search for levels using these songs either. This would be a neat feature to add.

**Comment by Prevter** [comment]
"Default Music Bypass" already does that, although you'd need to place the mp3 files inside your Resources folder
