### ISSUE TITLE
[Request] Custom bind to open menu

### ISSUE THREAD

**Issue by HumaanK** [Prevter/OpenHack#162]
In the settings button in the bottom left of the mod page ingame, can you add a feature that lets you customize the key used to open the hack, because I play on a Steam Deck, and unfortunately, there is no 'tab' button or whatever to open the menu.

**Comment by Rustring** [comment]
It is a thing right?

**Comment by Rustring** [comment]
Look at the bottom left

https://github.com/Prevter/OpenHack/blob/lemonade/screenshot.png

**Comment by TripleBaconn** [comment]
this exists though?????

**Comment by HumaanK** [comment]
> this exists though?????

Really? The last time I checked the OpenHack page it didn't have anything in the settings nor near it. I haven't installed OpenHack yet but I will see later on. I apologize for the misconceptions and appreciate the help. I will check this information.

**Comment by Prevter** [comment]
Currently, you can only change the keybind from within the menu, or by editing the config.json file. Geode mod settings do not contain that option, but it would be nice to add that just in case.

**Comment by HumaanK** [comment]
Update: I checked the image but the thing is, I can't open the menu to begin with because I cannot press 'tab', as I play on the Steam Deck. So what I'm saying is there should be a feature in the mod settings to change the key to open the menu aswell so people on other devices who don't have the 'tab' key can access the mod.

**Comment by HumaanK** [comment]
> Currently, you can only change the keybind from within the menu, or by editing the config.json file. Geode mod settings do not contain that option, but it would be nice to add that just in case.

OMG YESS the last time that i had this same issue with another client the owner just plugged their discord and didn't do anything, but you actually give support AND you (might) add that to the client which I appreciate very much. Your mod has certain hacks I have longed to use in my time of playing Geometry Dash. Thank you very much!

**Comment by TripleBaconn** [comment]
ignore me mentioning u, it was a misclick
i as tryna ask why u didnt close the issue if u have got an anser

**Comment by HumaanK** [comment]
> ignore me mentioning u, it was a misclick
> i as tryna ask why u didnt close the issue if u have got an anser

my bad homie ill close it now
