### ISSUE TITLE
[Request] Add support for changing gameplay keybinds

### ISSUE THREAD

**Issue by Master-64** [Prevter/OpenHack#166]
**Describe your idea.**
With the current keybind system implemented, add a way to rebind your gameplay keybinds.

**Examples.**
The ability to rebind your jump key off of the left mouse button and onto a different key.

**Comment by HumaanK** [comment]
theres another mod for this on geode i don't remember it's name but there definitely is one

**Comment by HumaanK** [comment]
and if you find it then close the issue

**Comment by Master-64** [comment]
You're right, this would be more hacky than anything, we should leave it up to the official Geode mod that handles this natively. Closing.
