### ISSUE TITLE
[Bug] crash on startup

### ISSUE THREAD

**Issue by Csparmaz** [Prevter/OpenHack#170]
It crashes on startup, before the update this didnt happen.

---------------------------
Geometry Dash Crashed
---------------------------
An exception had occured!
Tip: You can use 'CTRL + C' to copy this message.

== OpenHack information ==
- Version: 2.2.2.1
- Build date: Apr  7 2024 21:26:28
- Commit hash: f8a5a29
- Game version: 2.204
- Game path: D:\SteamLibrary\steamapps\common\Geometry Dash

== Exception Information ==
Exception code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception flags: 0
Exception address: 40400000 (40400000)
Number of parameters: 2

== Stack Trace ==
 - 40400000
 - 0118F3DC
 - MSVCR120.dll + 0x9ea6b (_RTDynamicCast + 0x77)
 - XINPUT9_1_0.dll + 0x1ccc6 (openhack::gui::from_json + 0x156)

== Registers ==
EAX: 000000c8
EBX: 58a98d97
ECX: 0118f3a8
EDX: 73aa123c
EBP: 00000000
ESP: 0118f3f4
EDI: 5889c8e6
ESI: 0118f3c0
EIP: 5889ccc6

---------------------------
OK   
---------------------------

**Comment by Prevter** [comment]
Reinstall from the [latest release](https://github.com/prevter/openhack/releases/latest).
