### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Djspac3** [Prevter/OpenHack#190]
#60 just another person asking for them though the ones that would BE GREAT jump hack, and show trajectory even tho the one referenced doesn't ask for it it's just nice

**Comment by cursedConLaVocalC** [comment]
meh auto clicker and jumphack wouldn't be added anyways

**Comment by Djspac3** [comment]
why?

**Comment by Noodlesy** [comment]
Auto clicker: just download one you dont have to use the mod
Jump hack: Just use the level edit hack to make a multi activate red orb follow you
