### ISSUE TITLE
Add A Status Dropout.

### ISSUE THREAD

**Issue by Zerawhistler** [Prevter/OpenHack#199]
**Describe your idea.**
Basically like in Mega Hack, The status dropout would include options like a clock, level time, fps counter, test mode etc. As a small watermark when you play a level.

**Examples.**
If you want to see the time right now but your geometry dash is in full screen, you can use the option "clock" to view the time similar to as megahack does it. Another example, if you want to see how long you are at a level, you can see it by clicking on the "level time" option

**Comment by Prevter** [comment]
Please check "Labels" tab in the menu, thank you

**Comment by Zerawhistler** [comment]
Thanks!

**Comment by Zerawhistler** [comment]
Something that happens is that when i Use the status, the game either crashes or freezes
