### ISSUE TITLE
[Bug] Music continues from where it left off after dying from a StartPos with the StartPosSwitcher

### ISSUE THREAD

**Issue by HumaanK** [Prevter/OpenHack#207]
**Describe the bug**
**Describe the bug**
When I am using the StartPos Switcher to go to a StartPos and I die in a level, the music keeps on continuing from where it left off.

**To Reproduce**
I placed a StartPos in Sh*tty Bloodbath at Evasium's part and I died and the music kept on playing from where I died instead of going back to the part of the song that plays at the beginning of Evasium's part.

**Expected behavior**
AWhen I died, I expected the song to go back to the part that plays at the beginning of Evasium.

**Screenshots**
Don't have screenshots but you can test it for yourself.

**Comment by Prevter** [comment]
It's a RobTop bug, can't fix at the moment.
And will probably be fixed by RobTop himself.
