### ISSUE TITLE
[Bug]I somehoe die at 63 on Cataclysm and it must have something to do with mod because when I deletred the mod it worked. Maybe the mod changes the physics but I dont have physics bypass or tps bypass on.

### ISSUE THREAD

**Issue by MaxMi1610GD** [Prevter/OpenHack#234]
**Describe the bug**

**To Reproduce**
What steps did you do to get this result?

**Expected behavior**

**Screenshots**

**Comment by Prevter** [comment]
it's a vanilla bug related to "Show Hitboxes".
you can either disable hitboxes, or get the beta build which fixes the issue from here:
https://github.com/Prevter/OpenHack/releases/tag/nightly

**Comment by MaxMi1610GD** [comment]
OMG THX
