### ISSUE TITLE
[Request] Rainbow Wave Trail and Adjust Wave Trail Size

### ISSUE THREAD

**Issue by Rustring** [Prevter/OpenHack#33]
Please add these features they would be game changers. Rainbow Icons would be a great idea as well.

**Comment by ghostlamma** [comment]
I agree, being able to change colors of the wave trail and trail size is really useful, though it might be a bit hard to implement.. reverse engineering isn't easy 😔, i tried to make that myself both manually and by using geode, didn't had a luck(my best was changing colors with some blending-function issues, and changing thickness but not pulse lol). Hopefully it gets added 🙏 .

**Comment by bennyd87708** [comment]
+1 for adjusting wave trail size - my old menu also used to have a "no wave pulse" setting, but the trail was thicker than when enabling the same setting with openhack. Would love to be able to match it with what I'm used to.

**Comment by Rustring** [comment]
It's added now idk why it isn't closed, I'ma close it right now
