### ISSUE TITLE
great work so far but read my description

### ISSUE THREAD

**Issue by ShawarmaKing7** [Prevter/OpenHack#41]
I love openhack it is great but i would like it if you made noclip accuracy, noclip deaths, and fps counter. 
Thanks.

**Comment by ItzMarioPlayz12** [comment]
if u didnt know, there's a built in fps counter in gd
![image](https://github.com/Prevter/GDOpenHack/assets/110222477/47e5e617-4e8c-4ffb-8c38-383a2f6c71bf)

**Comment by ShawarmaKing7** [comment]
still idc anyway add noclip accuracy and apply music changes to speedhack
