### ISSUE TITLE
Show hitboxes

### ISSUE THREAD

**Issue by Breelandthecat** [Prevter/OpenHack#44]
Hi, Could you please add "Show hitboxes"? I Know it exists in the game already, But ingame default, Its practice mode. Otherwise i like this

**Comment by Breelandthecat** [comment]
Hello? h

**Comment by Rustring** [comment]
Here is the link that has show hitboxes, from yesterday's commit (Geode only)
https://github.com/Prevter/GDOpenHack/actions/runs/8333240586/artifacts/1336656597
