### ISSUE TITLE
[Request] level uncompleter

### ISSUE THREAD

**Issue by QOQOQO2** [Prevter/OpenHack#57]
It uncompletes levels like in mega hack

steps:
So check if you did the level, And then check is it plat or classic. Then see how many stars it gives, and take away the stars and correct difficulty of demon. Maybe there is more but thats all I can think of.

**Comment by Aimbotish** [comment]
Yeah we really need that, I accidently beat a level with speedhack and for some reason it counted as a completion (I had safe mode on)

**Comment by Bituvo** [comment]
This already exists
