### ISSUE TITLE
Snap windows to corners when dragging them

### ISSUE THREAD

**Issue by silvernull** [Prevter/OpenHack#90]
**Describe your idea.**
Once again a missing feature that existed before 2.0 I believe.

**Examples.**
The hack menu windows at current snap back to their position with lock windows on and cannot be dragged and have them snap to each other's corners like you'd expect

Additionally when you press "Lock windows" the windows reset to their default positions instead of being locked at their current position

**Comment by Prevter** [comment]
Probably a naming issue, as "Lock Windows" primary function is to always reposition windows depending on scale changes, resolution changes, minimizing/maximizing windows, etc.
